apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc
  namespace: default
spec:
  selector:
    matchLabels:
      name: poc
  template:
    metadata:
      labels:
        name: poc
    spec:
      containers:
        #      - command:
        #        - bash
        #        - -c
        #        - tail -f /dev/null
      - env:
        - name: CONFIGMAPS_NAMESPACE
          value: default
        - name: CONFIGMAPS_NAME
          value: aliyun-oss-tf-state
        - name: TF_STATE_DIR
          value: /data/tfstate
        image: zzxwill/terraform-tfstate-retriever:v0.1
        imagePullPolicy: Always
        name: terraform-tfstate-retriever
